# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/threed_render_hw/threed_render_hw.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==threed_render_hw || ORIG_REF_NAME==threed_render_hw} -quiet] -quiet

# IP: bd/threed_render_hw/ip/threed_render_hw_processing_system7_0_0/threed_render_hw_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==threed_render_hw_processing_system7_0_0 || ORIG_REF_NAME==threed_render_hw_processing_system7_0_0} -quiet] -quiet

# IP: bd/threed_render_hw/ip/threed_render_hw_axi_mem_intercon_0/threed_render_hw_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==threed_render_hw_axi_mem_intercon_0 || ORIG_REF_NAME==threed_render_hw_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/threed_render_hw/ip/threed_render_hw_rst_ps7_0_100M_0/threed_render_hw_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==threed_render_hw_rst_ps7_0_100M_0 || ORIG_REF_NAME==threed_render_hw_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/threed_render_hw/ip/threed_render_hw_xbar_0/threed_render_hw_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==threed_render_hw_xbar_0 || ORIG_REF_NAME==threed_render_hw_xbar_0} -quiet] -quiet

# IP: bd/threed_render_hw/ip/threed_render_hw_ps7_0_axi_periph_0/threed_render_hw_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==threed_render_hw_ps7_0_axi_periph_0 || ORIG_REF_NAME==threed_render_hw_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/threed_render_hw/ip/threed_render_hw_threed_render_hls_0_0/threed_render_hw_threed_render_hls_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==threed_render_hw_threed_render_hls_0_0 || ORIG_REF_NAME==threed_render_hw_threed_render_hls_0_0} -quiet] -quiet

# IP: bd/threed_render_hw/ip/threed_render_hw_auto_pc_0/threed_render_hw_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==threed_render_hw_auto_pc_0 || ORIG_REF_NAME==threed_render_hw_auto_pc_0} -quiet] -quiet

# IP: bd/threed_render_hw/ip/threed_render_hw_auto_us_0/threed_render_hw_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==threed_render_hw_auto_us_0 || ORIG_REF_NAME==threed_render_hw_auto_us_0} -quiet] -quiet

# IP: bd/threed_render_hw/ip/threed_render_hw_auto_pc_1/threed_render_hw_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==threed_render_hw_auto_pc_1 || ORIG_REF_NAME==threed_render_hw_auto_pc_1} -quiet] -quiet

# XDC: e:/fpga/fpgacamp2023/threed_render/threed_render_hw/threed_render_hw.gen/sources_1/bd/threed_render_hw/threed_render_hw_ooc.xdc
