# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/fpga/fpgacamp2023/threed_render/threed_render_hw/threed_render_hw.srcs/sources_1/bd/threed_render_hw/ip/threed_render_hw_processing_system7_0_0/threed_render_hw_processing_system7_0_0.xci
# IP: The module: 'threed_render_hw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fpga/fpgacamp2023/threed_render/threed_render_hw/threed_render_hw.gen/sources_1/bd/threed_render_hw/ip/threed_render_hw_processing_system7_0_0/threed_render_hw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'threed_render_hw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/fpga/fpgacamp2023/threed_render/threed_render_hw/threed_render_hw.srcs/sources_1/bd/threed_render_hw/ip/threed_render_hw_processing_system7_0_0/threed_render_hw_processing_system7_0_0.xci
# IP: The module: 'threed_render_hw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/fpga/fpgacamp2023/threed_render/threed_render_hw/threed_render_hw.gen/sources_1/bd/threed_render_hw/ip/threed_render_hw_processing_system7_0_0/threed_render_hw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'threed_render_hw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
