// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module threed_render_hls_sin_or_cos_float_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        t_in,
        do_cos,
        ap_return
);

parameter    ap_ST_fsm_state1 = 23'd1;
parameter    ap_ST_fsm_state2 = 23'd2;
parameter    ap_ST_fsm_state3 = 23'd4;
parameter    ap_ST_fsm_state4 = 23'd8;
parameter    ap_ST_fsm_state5 = 23'd16;
parameter    ap_ST_fsm_state6 = 23'd32;
parameter    ap_ST_fsm_state7 = 23'd64;
parameter    ap_ST_fsm_state8 = 23'd128;
parameter    ap_ST_fsm_state9 = 23'd256;
parameter    ap_ST_fsm_state10 = 23'd512;
parameter    ap_ST_fsm_state11 = 23'd1024;
parameter    ap_ST_fsm_state12 = 23'd2048;
parameter    ap_ST_fsm_state13 = 23'd4096;
parameter    ap_ST_fsm_state14 = 23'd8192;
parameter    ap_ST_fsm_state15 = 23'd16384;
parameter    ap_ST_fsm_state16 = 23'd32768;
parameter    ap_ST_fsm_state17 = 23'd65536;
parameter    ap_ST_fsm_state18 = 23'd131072;
parameter    ap_ST_fsm_state19 = 23'd262144;
parameter    ap_ST_fsm_state20 = 23'd524288;
parameter    ap_ST_fsm_state21 = 23'd1048576;
parameter    ap_ST_fsm_state22 = 23'd2097152;
parameter    ap_ST_fsm_state23 = 23'd4194304;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] t_in;
input  [0:0] do_cos;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [22:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] ref_4oPi_table_100_V_address0;
reg    ref_4oPi_table_100_V_ce0;
wire   [99:0] ref_4oPi_table_100_V_q0;
wire   [7:0] second_order_float_sin_cos_K0_V_address0;
reg    second_order_float_sin_cos_K0_V_ce0;
wire   [29:0] second_order_float_sin_cos_K0_V_q0;
wire   [7:0] second_order_float_sin_cos_K1_V_address0;
reg    second_order_float_sin_cos_K1_V_ce0;
wire   [22:0] second_order_float_sin_cos_K1_V_q0;
wire   [7:0] second_order_float_sin_cos_K2_V_address0;
reg    second_order_float_sin_cos_K2_V_ce0;
wire  signed [14:0] second_order_float_sin_cos_K2_V_q0;
reg   [0:0] p_Result_58_reg_1193;
wire   [7:0] din_exp_V_fu_299_p4;
reg   [7:0] din_exp_V_reg_1199;
wire   [0:0] closepath_fu_313_p2;
reg   [0:0] closepath_reg_1206;
wire   [22:0] p_Result_59_fu_319_p1;
reg   [22:0] p_Result_59_reg_1213;
wire   [3:0] trunc_ln628_fu_352_p1;
reg   [3:0] trunc_ln628_reg_1223;
wire   [0:0] icmp_ln1019_1_fu_356_p2;
reg   [0:0] icmp_ln1019_1_reg_1228;
reg  signed [79:0] Med_V_reg_1234;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [79:0] grp_fu_392_p2;
reg   [79:0] ret_V_reg_1244;
wire    ap_CS_fsm_state7;
reg   [57:0] Mx_bits_V_reg_1249;
reg   [2:0] k_V_reg_1255;
wire   [57:0] Mx_bits_V_3_fu_440_p3;
reg   [57:0] Mx_bits_V_3_reg_1260;
wire    ap_CS_fsm_state8;
wire   [5:0] Mx_zeros_fu_495_p1;
reg   [5:0] Mx_zeros_reg_1265;
wire   [2:0] k_V_1_fu_511_p3;
reg   [2:0] k_V_1_reg_1271;
wire    ap_CS_fsm_state9;
reg   [28:0] Mx_V_reg_1277;
wire  signed [7:0] Ex_V_3_fu_538_p2;
reg  signed [7:0] Ex_V_3_reg_1283;
wire   [0:0] isNeg_fu_548_p3;
reg   [0:0] isNeg_reg_1288;
wire   [8:0] ush_fu_562_p3;
reg   [8:0] ush_reg_1293;
wire   [0:0] icmp_ln1019_fu_570_p2;
reg   [0:0] icmp_ln1019_reg_1298;
wire   [0:0] icmp_ln1019_2_fu_575_p2;
reg   [0:0] icmp_ln1019_2_reg_1304;
wire   [21:0] B_fu_605_p1;
reg   [21:0] B_reg_1312;
wire    ap_CS_fsm_state10;
reg   [6:0] tmp_12_reg_1317;
wire   [29:0] zext_ln1271_fu_629_p1;
wire    ap_CS_fsm_state12;
wire   [0:0] cos_basis_fu_660_p3;
reg   [0:0] cos_basis_reg_1334;
wire   [0:0] results_sign_V_3_fu_785_p2;
reg   [0:0] results_sign_V_3_reg_1355;
wire    ap_CS_fsm_state13;
reg   [28:0] t1_V_reg_1365;
reg  signed [22:0] second_order_float_sin_cos_K1_V_load_reg_1370;
wire   [0:0] and_ln300_fu_818_p2;
reg   [0:0] and_ln300_reg_1380;
wire   [0:0] results_sign_V_4_fu_832_p3;
reg   [0:0] results_sign_V_4_reg_1386;
reg   [21:0] rhs_16_reg_1391;
wire    ap_CS_fsm_state14;
wire   [28:0] Mx_V_1_fu_861_p3;
reg   [28:0] Mx_V_1_reg_1396;
wire    ap_CS_fsm_state16;
wire   [29:0] ret_V_34_fu_892_p2;
reg  signed [29:0] ret_V_34_reg_1401;
wire    ap_CS_fsm_state17;
reg   [28:0] result_V_reg_1416;
wire    ap_CS_fsm_state18;
reg   [15:0] tmp_13_reg_1422;
reg   [12:0] tmp_14_reg_1427;
wire   [31:0] p_Result_64_fu_940_p3;
reg   [31:0] p_Result_64_reg_1432;
wire    ap_CS_fsm_state19;
wire   [31:0] p_Result_65_fu_948_p3;
reg   [31:0] p_Result_65_reg_1437;
wire   [0:0] icmp_ln1653_fu_964_p2;
reg   [0:0] icmp_ln1653_reg_1448;
wire    ap_CS_fsm_state21;
wire   [0:0] grp_sin_or_cos_float_Pipeline_2_fu_276_ap_return;
reg   [0:0] targetBlock_reg_1453;
wire    ap_CS_fsm_state22;
wire    grp_sin_or_cos_float_Pipeline_1_fu_268_ap_start;
wire    grp_sin_or_cos_float_Pipeline_1_fu_268_ap_done;
wire    grp_sin_or_cos_float_Pipeline_1_fu_268_ap_idle;
wire    grp_sin_or_cos_float_Pipeline_1_fu_268_ap_ready;
wire   [31:0] grp_sin_or_cos_float_Pipeline_1_fu_268_c_0_023_out;
wire    grp_sin_or_cos_float_Pipeline_1_fu_268_c_0_023_out_ap_vld;
wire   [31:0] grp_sin_or_cos_float_Pipeline_1_fu_268_c_1_022_out;
wire    grp_sin_or_cos_float_Pipeline_1_fu_268_c_1_022_out_ap_vld;
wire    grp_sin_or_cos_float_Pipeline_2_fu_276_ap_start;
wire    grp_sin_or_cos_float_Pipeline_2_fu_276_ap_done;
wire    grp_sin_or_cos_float_Pipeline_2_fu_276_ap_idle;
wire    grp_sin_or_cos_float_Pipeline_2_fu_276_ap_ready;
wire   [31:0] grp_sin_or_cos_float_Pipeline_2_fu_276_shift_out;
wire    grp_sin_or_cos_float_Pipeline_2_fu_276_shift_out_ap_vld;
wire   [27:0] grp_sin_or_cos_float_Pipeline_2_fu_276_in_shift_V_1_cast_out;
wire    grp_sin_or_cos_float_Pipeline_2_fu_276_in_shift_V_1_cast_out_ap_vld;
wire   [31:0] grp_sin_or_cos_float_Pipeline_2_fu_276_shift_1_out;
wire    grp_sin_or_cos_float_Pipeline_2_fu_276_shift_1_out_ap_vld;
wire   [27:0] grp_sin_or_cos_float_Pipeline_2_fu_276_trunc_ln10_out;
wire    grp_sin_or_cos_float_Pipeline_2_fu_276_trunc_ln10_out_ap_vld;
reg    grp_sin_or_cos_float_Pipeline_1_fu_268_ap_start_reg;
wire    ap_CS_fsm_state20;
reg    grp_sin_or_cos_float_Pipeline_2_fu_276_ap_start_reg;
reg   [31:0] shift_loc_fu_192;
reg   [27:0] in_shift_V_1_cast_loc_fu_188;
reg   [31:0] shift_1_loc_fu_184;
reg   [27:0] trunc_ln10_loc_fu_180;
wire   [63:0] zext_ln541_1_fu_347_p1;
wire   [63:0] zext_ln541_fu_683_p1;
wire    ap_CS_fsm_state23;
wire   [31:0] data_V_fu_287_p1;
wire   [7:0] add_ln214_fu_323_p2;
wire   [7:0] addr_V_fu_329_p3;
wire   [3:0] lshr_ln_fu_337_p4;
wire   [22:0] din_sig_V_fu_309_p1;
wire   [99:0] zext_ln930_fu_362_p1;
wire   [99:0] r_V_38_fu_365_p2;
wire   [23:0] p_Result_60_fu_381_p3;
wire   [23:0] grp_fu_392_p1;
wire   [0:0] tmp_fu_417_p3;
wire   [0:0] xor_ln1027_fu_424_p2;
wire   [0:0] p_Result_s_fu_429_p2;
wire   [57:0] Mx_bits_V_1_fu_435_p2;
wire   [28:0] tmp_11_fu_447_p4;
wire   [29:0] p_Result_61_fu_457_p3;
reg   [29:0] p_Result_49_fu_465_p4;
wire   [30:0] p_Result_62_fu_475_p3;
wire  signed [31:0] sext_ln1198_fu_483_p1;
reg   [31:0] op_assign_fu_487_p3;
wire   [7:0] Ex_V_fu_499_p2;
wire   [57:0] zext_ln1454_fu_520_p1;
wire   [57:0] r_fu_523_p2;
wire   [7:0] select_ln482_fu_504_p3;
wire   [7:0] zext_ln841_fu_517_p1;
wire  signed [8:0] sext_ln1535_fu_544_p1;
wire   [8:0] sub_ln1512_fu_556_p2;
wire   [31:0] zext_ln1488_fu_583_p1;
wire  signed [31:0] sext_ln1512_fu_580_p1;
wire   [31:0] lshr_ln1488_fu_586_p2;
wire   [31:0] shl_ln1454_fu_592_p2;
wire   [31:0] select_ln1513_fu_598_p3;
wire   [14:0] B_trunc_fu_619_p4;
wire   [0:0] tmp_s_fu_633_p10;
wire   [0:0] xor_ln271_fu_654_p2;
wire   [0:0] sin_basis_fu_668_p3;
wire   [7:0] p_Result_63_fu_676_p3;
wire   [3:0] p_Result_66_fu_690_p3;
wire   [0:0] tmp_15_fu_696_p18;
wire   [0:0] tmp_16_fu_734_p18;
wire   [0:0] results_sign_V_fu_772_p3;
wire   [0:0] xor_ln311_fu_780_p2;
wire   [29:0] B_squared_fu_791_p1;
wire  signed [29:0] grp_fu_1143_p2;
wire   [14:0] B_squared_fu_791_p4;
wire   [0:0] xor_ln307_fu_822_p2;
wire   [0:0] results_sign_V_2_fu_827_p2;
wire   [21:0] r_V_33_fu_845_p1;
wire   [44:0] r_V_33_fu_845_p2;
wire  signed [29:0] grp_fu_1150_p2;
wire  signed [29:0] sext_ln813_fu_876_p1;
wire  signed [29:0] sext_ln813_7_fu_879_p1;
wire   [13:0] rhs_1_fu_867_p4;
wire   [29:0] ret_V_33_fu_882_p2;
wire  signed [29:0] sext_ln1347_fu_888_p1;
wire   [28:0] grp_fu_904_p1;
wire   [57:0] grp_fu_904_p2;
wire   [7:0] Ex_V_4_fu_969_p3;
wire  signed [8:0] sext_ln186_fu_975_p1;
wire   [8:0] add_ln329_fu_998_p2;
wire  signed [31:0] sext_ln329_fu_1004_p1;
wire   [31:0] select_ln318_fu_991_p3;
wire   [31:0] newexp_fu_1008_p2;
wire   [0:0] tmp_42_fu_1014_p3;
wire   [22:0] tmp_43_fu_1027_p4;
wire   [22:0] tmp_44_fu_1037_p4;
wire   [0:0] or_ln335_fu_1022_p2;
wire   [0:0] or_ln311_fu_1072_p2;
wire   [7:0] select_ln311_fu_1065_p3;
wire   [7:0] empty_fu_1054_p1;
wire   [7:0] select_ln288_fu_1058_p3;
wire   [7:0] results_exp_V_1_fu_1077_p3;
wire   [0:0] and_ln300_1_fu_1092_p2;
wire   [0:0] xor_ln300_fu_1096_p2;
wire   [22:0] select_ln318_1_fu_1047_p3;
wire   [0:0] or_ln300_fu_1110_p2;
wire   [22:0] select_ln300_3_fu_1102_p3;
wire   [22:0] select_ln300_fu_1114_p3;
wire   [7:0] results_exp_V_fu_1085_p3;
wire   [22:0] results_sig_V_fu_1122_p3;
wire   [31:0] p_Result_67_fu_1130_p4;
wire   [14:0] grp_fu_1143_p0;
wire   [14:0] grp_fu_1143_p1;
wire   [14:0] grp_fu_1150_p0;
reg   [22:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire   [29:0] grp_fu_1150_p00;
wire   [79:0] grp_fu_392_p10;
wire   [57:0] grp_fu_904_p10;
wire   [44:0] r_V_33_fu_845_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 23'd1;
#0 grp_sin_or_cos_float_Pipeline_1_fu_268_ap_start_reg = 1'b0;
#0 grp_sin_or_cos_float_Pipeline_2_fu_276_ap_start_reg = 1'b0;
end

threed_render_hls_sin_or_cos_float_s_ref_4oPi_table_100_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 100 ),
    .AddressRange( 13 ),
    .AddressWidth( 4 ))
ref_4oPi_table_100_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_100_V_address0),
    .ce0(ref_4oPi_table_100_V_ce0),
    .q0(ref_4oPi_table_100_V_q0)
);

threed_render_hls_sin_or_cos_float_s_second_order_float_sin_cos_K0_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 30 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K0_V_address0),
    .ce0(second_order_float_sin_cos_K0_V_ce0),
    .q0(second_order_float_sin_cos_K0_V_q0)
);

threed_render_hls_sin_or_cos_float_s_second_order_float_sin_cos_K1_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 23 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K1_V_address0),
    .ce0(second_order_float_sin_cos_K1_V_ce0),
    .q0(second_order_float_sin_cos_K1_V_q0)
);

threed_render_hls_sin_or_cos_float_s_second_order_float_sin_cos_K2_V_ROM_1P_LUTRAM_1R #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K2_V_address0),
    .ce0(second_order_float_sin_cos_K2_V_ce0),
    .q0(second_order_float_sin_cos_K2_V_q0)
);

threed_render_hls_sin_or_cos_float_Pipeline_1 grp_sin_or_cos_float_Pipeline_1_fu_268(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_float_Pipeline_1_fu_268_ap_start),
    .ap_done(grp_sin_or_cos_float_Pipeline_1_fu_268_ap_done),
    .ap_idle(grp_sin_or_cos_float_Pipeline_1_fu_268_ap_idle),
    .ap_ready(grp_sin_or_cos_float_Pipeline_1_fu_268_ap_ready),
    .p_Result_88(p_Result_65_reg_1437),
    .p_Result_87(p_Result_64_reg_1432),
    .c_0_023_out(grp_sin_or_cos_float_Pipeline_1_fu_268_c_0_023_out),
    .c_0_023_out_ap_vld(grp_sin_or_cos_float_Pipeline_1_fu_268_c_0_023_out_ap_vld),
    .c_1_022_out(grp_sin_or_cos_float_Pipeline_1_fu_268_c_1_022_out),
    .c_1_022_out_ap_vld(grp_sin_or_cos_float_Pipeline_1_fu_268_c_1_022_out_ap_vld)
);

threed_render_hls_sin_or_cos_float_Pipeline_2 grp_sin_or_cos_float_Pipeline_2_fu_276(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_float_Pipeline_2_fu_276_ap_start),
    .ap_done(grp_sin_or_cos_float_Pipeline_2_fu_276_ap_done),
    .ap_idle(grp_sin_or_cos_float_Pipeline_2_fu_276_ap_idle),
    .ap_ready(grp_sin_or_cos_float_Pipeline_2_fu_276_ap_ready),
    .result_V(result_V_reg_1416),
    .c_1_022_reload(grp_sin_or_cos_float_Pipeline_1_fu_268_c_1_022_out),
    .c_0_023_reload(grp_sin_or_cos_float_Pipeline_1_fu_268_c_0_023_out),
    .shift_out(grp_sin_or_cos_float_Pipeline_2_fu_276_shift_out),
    .shift_out_ap_vld(grp_sin_or_cos_float_Pipeline_2_fu_276_shift_out_ap_vld),
    .in_shift_V_1_cast_out(grp_sin_or_cos_float_Pipeline_2_fu_276_in_shift_V_1_cast_out),
    .in_shift_V_1_cast_out_ap_vld(grp_sin_or_cos_float_Pipeline_2_fu_276_in_shift_V_1_cast_out_ap_vld),
    .shift_1_out(grp_sin_or_cos_float_Pipeline_2_fu_276_shift_1_out),
    .shift_1_out_ap_vld(grp_sin_or_cos_float_Pipeline_2_fu_276_shift_1_out_ap_vld),
    .trunc_ln10_out(grp_sin_or_cos_float_Pipeline_2_fu_276_trunc_ln10_out),
    .trunc_ln10_out_ap_vld(grp_sin_or_cos_float_Pipeline_2_fu_276_trunc_ln10_out_ap_vld),
    .ap_return(grp_sin_or_cos_float_Pipeline_2_fu_276_ap_return)
);

threed_render_hls_mul_80s_24ns_80_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 80 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 80 ))
mul_80s_24ns_80_5_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Med_V_reg_1234),
    .din1(grp_fu_392_p1),
    .ce(1'b1),
    .dout(grp_fu_392_p2)
);

threed_render_hls_mux_83_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
mux_83_1_1_1_U13(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(k_V_1_reg_1271),
    .dout(tmp_s_fu_633_p10)
);

threed_render_hls_mux_164_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
mux_164_1_1_1_U14(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_66_fu_690_p3),
    .dout(tmp_15_fu_696_p18)
);

threed_render_hls_mux_164_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
mux_164_1_1_1_U15(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_66_fu_690_p3),
    .dout(tmp_16_fu_734_p18)
);

threed_render_hls_mul_23s_22ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 45 ))
mul_23s_22ns_45_1_1_U16(
    .din0(second_order_float_sin_cos_K1_V_load_reg_1370),
    .din1(r_V_33_fu_845_p1),
    .dout(r_V_33_fu_845_p2)
);

threed_render_hls_mul_30s_29ns_58_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 58 ))
mul_30s_29ns_58_2_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_34_reg_1401),
    .din1(grp_fu_904_p1),
    .ce(1'b1),
    .dout(grp_fu_904_p2)
);

threed_render_hls_mul_mul_15ns_15ns_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_mul_15ns_15ns_30_4_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1143_p0),
    .din1(grp_fu_1143_p1),
    .ce(1'b1),
    .dout(grp_fu_1143_p2)
);

threed_render_hls_mul_mul_15ns_15s_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_mul_15ns_15s_30_4_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1150_p0),
    .din1(second_order_float_sin_cos_K2_V_q0),
    .ce(1'b1),
    .dout(grp_fu_1150_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_float_Pipeline_1_fu_268_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_sin_or_cos_float_Pipeline_1_fu_268_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_float_Pipeline_1_fu_268_ap_ready == 1'b1)) begin
            grp_sin_or_cos_float_Pipeline_1_fu_268_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_float_Pipeline_2_fu_276_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            grp_sin_or_cos_float_Pipeline_2_fu_276_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_float_Pipeline_2_fu_276_ap_ready == 1'b1)) begin
            grp_sin_or_cos_float_Pipeline_2_fu_276_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        B_reg_1312 <= B_fu_605_p1;
        tmp_12_reg_1317 <= {{select_ln1513_fu_598_p3[28:22]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        Ex_V_3_reg_1283 <= Ex_V_3_fu_538_p2;
        Mx_V_reg_1277 <= {{r_fu_523_p2[57:29]}};
        icmp_ln1019_2_reg_1304 <= icmp_ln1019_2_fu_575_p2;
        icmp_ln1019_reg_1298 <= icmp_ln1019_fu_570_p2;
        isNeg_reg_1288 <= Ex_V_3_fu_538_p2[32'd7];
        k_V_1_reg_1271 <= k_V_1_fu_511_p3;
        ush_reg_1293 <= ush_fu_562_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Med_V_reg_1234 <= {{r_V_38_fu_365_p2[99:20]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        Mx_V_1_reg_1396 <= Mx_V_1_fu_861_p3;
        ret_V_34_reg_1401 <= ret_V_34_fu_892_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        Mx_bits_V_3_reg_1260 <= Mx_bits_V_3_fu_440_p3;
        Mx_zeros_reg_1265 <= Mx_zeros_fu_495_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Mx_bits_V_reg_1249 <= {{grp_fu_392_p2[76:19]}};
        ret_V_reg_1244 <= grp_fu_392_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        and_ln300_reg_1380 <= and_ln300_fu_818_p2;
        results_sign_V_4_reg_1386 <= results_sign_V_4_fu_832_p3;
        second_order_float_sin_cos_K1_V_load_reg_1370 <= second_order_float_sin_cos_K1_V_q0;
        t1_V_reg_1365 <= {{second_order_float_sin_cos_K0_V_q0[29:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        closepath_reg_1206 <= closepath_fu_313_p2;
        din_exp_V_reg_1199 <= {{data_V_fu_287_p1[30:23]}};
        icmp_ln1019_1_reg_1228 <= icmp_ln1019_1_fu_356_p2;
        p_Result_58_reg_1193 <= data_V_fu_287_p1[32'd31];
        p_Result_59_reg_1213 <= p_Result_59_fu_319_p1;
        trunc_ln628_reg_1223 <= trunc_ln628_fu_352_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        cos_basis_reg_1334 <= cos_basis_fu_660_p3;
        results_sign_V_3_reg_1355 <= results_sign_V_3_fu_785_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        icmp_ln1653_reg_1448 <= icmp_ln1653_fu_964_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_or_cos_float_Pipeline_2_fu_276_in_shift_V_1_cast_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        in_shift_V_1_cast_loc_fu_188 <= grp_sin_or_cos_float_Pipeline_2_fu_276_in_shift_V_1_cast_out;
    end
end

always @ (posedge ap_clk) begin
    if (((closepath_reg_1206 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        k_V_reg_1255 <= {{grp_fu_392_p2[79:77]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        p_Result_64_reg_1432[31 : 16] <= p_Result_64_fu_940_p3[31 : 16];
        p_Result_65_reg_1437[31 : 19] <= p_Result_65_fu_948_p3[31 : 19];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        result_V_reg_1416 <= {{grp_fu_904_p2[57:29]}};
        tmp_13_reg_1422 <= {{grp_fu_904_p2[57:42]}};
        tmp_14_reg_1427 <= {{grp_fu_904_p2[41:29]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        rhs_16_reg_1391 <= {{r_V_33_fu_845_p2[44:23]}};
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_or_cos_float_Pipeline_2_fu_276_shift_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        shift_1_loc_fu_184 <= grp_sin_or_cos_float_Pipeline_2_fu_276_shift_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_or_cos_float_Pipeline_2_fu_276_shift_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        shift_loc_fu_192 <= grp_sin_or_cos_float_Pipeline_2_fu_276_shift_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        targetBlock_reg_1453 <= grp_sin_or_cos_float_Pipeline_2_fu_276_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_or_cos_float_Pipeline_2_fu_276_trunc_ln10_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        trunc_ln10_loc_fu_180 <= grp_sin_or_cos_float_Pipeline_2_fu_276_trunc_ln10_out;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_sin_or_cos_float_Pipeline_1_fu_268_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((grp_sin_or_cos_float_Pipeline_2_fu_276_ap_done == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ref_4oPi_table_100_V_ce0 = 1'b1;
    end else begin
        ref_4oPi_table_100_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        second_order_float_sin_cos_K0_V_ce0 = 1'b1;
    end else begin
        second_order_float_sin_cos_K0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        second_order_float_sin_cos_K1_V_ce0 = 1'b1;
    end else begin
        second_order_float_sin_cos_K1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        second_order_float_sin_cos_K2_V_ce0 = 1'b1;
    end else begin
        second_order_float_sin_cos_K2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_sin_or_cos_float_Pipeline_1_fu_268_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((grp_sin_or_cos_float_Pipeline_2_fu_276_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_fu_605_p1 = select_ln1513_fu_598_p3[21:0];

assign B_squared_fu_791_p1 = grp_fu_1143_p2;

assign B_squared_fu_791_p4 = {{B_squared_fu_791_p1[29:15]}};

assign B_trunc_fu_619_p4 = {{select_ln1513_fu_598_p3[21:7]}};

assign Ex_V_3_fu_538_p2 = (select_ln482_fu_504_p3 - zext_ln841_fu_517_p1);

assign Ex_V_4_fu_969_p3 = ((cos_basis_reg_1334[0:0] == 1'b1) ? 8'd0 : Ex_V_3_reg_1283);

assign Ex_V_fu_499_p2 = ($signed(din_exp_V_reg_1199) + $signed(8'd131));

assign Mx_V_1_fu_861_p3 = ((cos_basis_reg_1334[0:0] == 1'b1) ? 29'd536870911 : Mx_V_reg_1277);

assign Mx_bits_V_1_fu_435_p2 = (58'd0 - Mx_bits_V_reg_1249);

assign Mx_bits_V_3_fu_440_p3 = ((p_Result_s_fu_429_p2[0:0] == 1'b1) ? Mx_bits_V_1_fu_435_p2 : Mx_bits_V_reg_1249);

assign Mx_zeros_fu_495_p1 = op_assign_fu_487_p3[5:0];

assign add_ln214_fu_323_p2 = ($signed(din_exp_V_fu_299_p4) + $signed(8'd194));

assign add_ln329_fu_998_p2 = ($signed(sext_ln186_fu_975_p1) + $signed(9'd127));

assign addr_V_fu_329_p3 = ((closepath_fu_313_p2[0:0] == 1'b1) ? 8'd63 : add_ln214_fu_323_p2);

assign and_ln300_1_fu_1092_p2 = (icmp_ln1019_reg_1298 & icmp_ln1019_1_reg_1228);

assign and_ln300_fu_818_p2 = (icmp_ln1019_reg_1298 & icmp_ln1019_1_reg_1228);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = p_Result_67_fu_1130_p4;

assign closepath_fu_313_p2 = ((din_exp_V_fu_299_p4 < 8'd126) ? 1'b1 : 1'b0);

assign cos_basis_fu_660_p3 = ((do_cos[0:0] == 1'b1) ? xor_ln271_fu_654_p2 : tmp_s_fu_633_p10);

assign data_V_fu_287_p1 = t_in;

assign din_exp_V_fu_299_p4 = {{data_V_fu_287_p1[30:23]}};

assign din_sig_V_fu_309_p1 = data_V_fu_287_p1[22:0];

assign empty_fu_1054_p1 = newexp_fu_1008_p2[7:0];

assign grp_fu_1143_p0 = zext_ln1271_fu_629_p1;

assign grp_fu_1143_p1 = zext_ln1271_fu_629_p1;

assign grp_fu_1150_p0 = grp_fu_1150_p00;

assign grp_fu_1150_p00 = B_squared_fu_791_p4;

assign grp_fu_392_p1 = grp_fu_392_p10;

assign grp_fu_392_p10 = p_Result_60_fu_381_p3;

assign grp_fu_904_p1 = grp_fu_904_p10;

assign grp_fu_904_p10 = Mx_V_1_reg_1396;

assign grp_sin_or_cos_float_Pipeline_1_fu_268_ap_start = grp_sin_or_cos_float_Pipeline_1_fu_268_ap_start_reg;

assign grp_sin_or_cos_float_Pipeline_2_fu_276_ap_start = grp_sin_or_cos_float_Pipeline_2_fu_276_ap_start_reg;

assign icmp_ln1019_1_fu_356_p2 = ((din_sig_V_fu_309_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_2_fu_575_p2 = ((din_exp_V_reg_1199 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1019_fu_570_p2 = ((din_exp_V_reg_1199 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln1653_fu_964_p2 = ((result_V_reg_1416 == 29'd0) ? 1'b1 : 1'b0);

assign isNeg_fu_548_p3 = Ex_V_3_fu_538_p2[32'd7];

assign k_V_1_fu_511_p3 = ((closepath_reg_1206[0:0] == 1'b1) ? 3'd0 : k_V_reg_1255);

assign lshr_ln1488_fu_586_p2 = zext_ln1488_fu_583_p1 >> sext_ln1512_fu_580_p1;

assign lshr_ln_fu_337_p4 = {{addr_V_fu_329_p3[7:4]}};

assign newexp_fu_1008_p2 = ($signed(sext_ln329_fu_1004_p1) - $signed(select_ln318_fu_991_p3));


always @ (sext_ln1198_fu_483_p1) begin
    if (sext_ln1198_fu_483_p1[0] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd0;
    end else if (sext_ln1198_fu_483_p1[1] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd1;
    end else if (sext_ln1198_fu_483_p1[2] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd2;
    end else if (sext_ln1198_fu_483_p1[3] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd3;
    end else if (sext_ln1198_fu_483_p1[4] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd4;
    end else if (sext_ln1198_fu_483_p1[5] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd5;
    end else if (sext_ln1198_fu_483_p1[6] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd6;
    end else if (sext_ln1198_fu_483_p1[7] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd7;
    end else if (sext_ln1198_fu_483_p1[8] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd8;
    end else if (sext_ln1198_fu_483_p1[9] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd9;
    end else if (sext_ln1198_fu_483_p1[10] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd10;
    end else if (sext_ln1198_fu_483_p1[11] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd11;
    end else if (sext_ln1198_fu_483_p1[12] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd12;
    end else if (sext_ln1198_fu_483_p1[13] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd13;
    end else if (sext_ln1198_fu_483_p1[14] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd14;
    end else if (sext_ln1198_fu_483_p1[15] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd15;
    end else if (sext_ln1198_fu_483_p1[16] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd16;
    end else if (sext_ln1198_fu_483_p1[17] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd17;
    end else if (sext_ln1198_fu_483_p1[18] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd18;
    end else if (sext_ln1198_fu_483_p1[19] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd19;
    end else if (sext_ln1198_fu_483_p1[20] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd20;
    end else if (sext_ln1198_fu_483_p1[21] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd21;
    end else if (sext_ln1198_fu_483_p1[22] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd22;
    end else if (sext_ln1198_fu_483_p1[23] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd23;
    end else if (sext_ln1198_fu_483_p1[24] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd24;
    end else if (sext_ln1198_fu_483_p1[25] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd25;
    end else if (sext_ln1198_fu_483_p1[26] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd26;
    end else if (sext_ln1198_fu_483_p1[27] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd27;
    end else if (sext_ln1198_fu_483_p1[28] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd28;
    end else if (sext_ln1198_fu_483_p1[29] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd29;
    end else if (sext_ln1198_fu_483_p1[30] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd30;
    end else if (sext_ln1198_fu_483_p1[31] == 1'b1) begin
        op_assign_fu_487_p3 = 32'd31;
    end else begin
        op_assign_fu_487_p3 = 32'd32;
    end
end

assign or_ln300_fu_1110_p2 = (icmp_ln1019_2_reg_1304 | and_ln300_reg_1380);

assign or_ln311_fu_1072_p2 = (or_ln335_fu_1022_p2 | icmp_ln1019_2_reg_1304);

assign or_ln335_fu_1022_p2 = (tmp_42_fu_1014_p3 | icmp_ln1653_reg_1448);

integer ap_tvar_int_0;

always @ (p_Result_61_fu_457_p3) begin
    for (ap_tvar_int_0 = 30 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 29 - 0) begin
            p_Result_49_fu_465_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_49_fu_465_p4[ap_tvar_int_0] = p_Result_61_fu_457_p3[29 - ap_tvar_int_0];
        end
    end
end

assign p_Result_59_fu_319_p1 = data_V_fu_287_p1[22:0];

assign p_Result_60_fu_381_p3 = {{1'd1}, {p_Result_59_reg_1213}};

assign p_Result_61_fu_457_p3 = {{tmp_11_fu_447_p4}, {1'd1}};

assign p_Result_62_fu_475_p3 = {{1'd1}, {p_Result_49_fu_465_p4}};

assign p_Result_63_fu_676_p3 = {{sin_basis_fu_668_p3}, {tmp_12_reg_1317}};

assign p_Result_64_fu_940_p3 = {{tmp_13_reg_1422}, {16'd32768}};

assign p_Result_65_fu_948_p3 = {{tmp_14_reg_1427}, {19'd262144}};

assign p_Result_66_fu_690_p3 = {{p_Result_58_reg_1193}, {k_V_1_reg_1271}};

assign p_Result_67_fu_1130_p4 = {{{results_sign_V_4_reg_1386}, {results_exp_V_fu_1085_p3}}, {results_sig_V_fu_1122_p3}};

assign p_Result_s_fu_429_p2 = (xor_ln1027_fu_424_p2 & tmp_fu_417_p3);

assign r_V_33_fu_845_p1 = r_V_33_fu_845_p10;

assign r_V_33_fu_845_p10 = B_reg_1312;

assign r_V_38_fu_365_p2 = ref_4oPi_table_100_V_q0 << zext_ln930_fu_362_p1;

assign r_fu_523_p2 = Mx_bits_V_3_reg_1260 << zext_ln1454_fu_520_p1;

assign ref_4oPi_table_100_V_address0 = zext_ln541_1_fu_347_p1;

assign results_exp_V_1_fu_1077_p3 = ((or_ln311_fu_1072_p2[0:0] == 1'b1) ? select_ln311_fu_1065_p3 : empty_fu_1054_p1);

assign results_exp_V_fu_1085_p3 = ((and_ln300_reg_1380[0:0] == 1'b1) ? select_ln288_fu_1058_p3 : results_exp_V_1_fu_1077_p3);

assign results_sig_V_fu_1122_p3 = ((or_ln300_fu_1110_p2[0:0] == 1'b1) ? select_ln300_3_fu_1102_p3 : select_ln300_fu_1114_p3);

assign results_sign_V_2_fu_827_p2 = (xor_ln307_fu_822_p2 & p_Result_58_reg_1193);

assign results_sign_V_3_fu_785_p2 = (xor_ln311_fu_780_p2 & results_sign_V_fu_772_p3);

assign results_sign_V_4_fu_832_p3 = ((and_ln300_fu_818_p2[0:0] == 1'b1) ? results_sign_V_2_fu_827_p2 : results_sign_V_3_reg_1355);

assign results_sign_V_fu_772_p3 = ((cos_basis_fu_660_p3[0:0] == 1'b1) ? tmp_15_fu_696_p18 : tmp_16_fu_734_p18);

assign ret_V_33_fu_882_p2 = ($signed(sext_ln813_fu_876_p1) + $signed(sext_ln813_7_fu_879_p1));

assign ret_V_34_fu_892_p2 = ($signed(ret_V_33_fu_882_p2) + $signed(sext_ln1347_fu_888_p1));

assign rhs_1_fu_867_p4 = {{grp_fu_1150_p2[29:16]}};

assign second_order_float_sin_cos_K0_V_address0 = zext_ln541_fu_683_p1;

assign second_order_float_sin_cos_K1_V_address0 = zext_ln541_fu_683_p1;

assign second_order_float_sin_cos_K2_V_address0 = zext_ln541_fu_683_p1;

assign select_ln1513_fu_598_p3 = ((isNeg_reg_1288[0:0] == 1'b1) ? lshr_ln1488_fu_586_p2 : shl_ln1454_fu_592_p2);

assign select_ln288_fu_1058_p3 = ((do_cos[0:0] == 1'b1) ? 8'd127 : 8'd0);

assign select_ln300_3_fu_1102_p3 = ((xor_ln300_fu_1096_p2[0:0] == 1'b1) ? 23'd8388607 : 23'd0);

assign select_ln300_fu_1114_p3 = ((or_ln335_fu_1022_p2[0:0] == 1'b1) ? 23'd0 : select_ln318_1_fu_1047_p3);

assign select_ln311_fu_1065_p3 = ((icmp_ln1019_2_reg_1304[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln318_1_fu_1047_p3 = ((targetBlock_reg_1453[0:0] == 1'b1) ? tmp_43_fu_1027_p4 : tmp_44_fu_1037_p4);

assign select_ln318_fu_991_p3 = ((targetBlock_reg_1453[0:0] == 1'b1) ? shift_loc_fu_192 : shift_1_loc_fu_184);

assign select_ln482_fu_504_p3 = ((closepath_reg_1206[0:0] == 1'b1) ? Ex_V_fu_499_p2 : 8'd0);

assign sext_ln1198_fu_483_p1 = $signed(p_Result_62_fu_475_p3);

assign sext_ln1347_fu_888_p1 = $signed(rhs_1_fu_867_p4);

assign sext_ln1512_fu_580_p1 = $signed(ush_reg_1293);

assign sext_ln1535_fu_544_p1 = Ex_V_3_fu_538_p2;

assign sext_ln186_fu_975_p1 = $signed(Ex_V_4_fu_969_p3);

assign sext_ln329_fu_1004_p1 = $signed(add_ln329_fu_998_p2);

assign sext_ln813_7_fu_879_p1 = $signed(rhs_16_reg_1391);

assign sext_ln813_fu_876_p1 = $signed(t1_V_reg_1365);

assign shl_ln1454_fu_592_p2 = zext_ln1488_fu_583_p1 << sext_ln1512_fu_580_p1;

assign sin_basis_fu_668_p3 = ((do_cos[0:0] == 1'b1) ? tmp_s_fu_633_p10 : xor_ln271_fu_654_p2);

assign sub_ln1512_fu_556_p2 = ($signed(9'd0) - $signed(sext_ln1535_fu_544_p1));

assign tmp_11_fu_447_p4 = {{Mx_bits_V_3_fu_440_p3[57:29]}};

assign tmp_42_fu_1014_p3 = newexp_fu_1008_p2[32'd31];

assign tmp_43_fu_1027_p4 = {{in_shift_V_1_cast_loc_fu_188[27:5]}};

assign tmp_44_fu_1037_p4 = {{trunc_ln10_loc_fu_180[27:5]}};

assign tmp_fu_417_p3 = ret_V_reg_1244[32'd77];

assign trunc_ln628_fu_352_p1 = addr_V_fu_329_p3[3:0];

assign ush_fu_562_p3 = ((isNeg_fu_548_p3[0:0] == 1'b1) ? sub_ln1512_fu_556_p2 : sext_ln1535_fu_544_p1);

assign xor_ln1027_fu_424_p2 = (closepath_reg_1206 ^ 1'd1);

assign xor_ln271_fu_654_p2 = (tmp_s_fu_633_p10 ^ 1'd1);

assign xor_ln300_fu_1096_p2 = (1'd1 ^ and_ln300_1_fu_1092_p2);

assign xor_ln307_fu_822_p2 = (do_cos ^ 1'd1);

assign xor_ln311_fu_780_p2 = (icmp_ln1019_2_reg_1304 ^ 1'd1);

assign zext_ln1271_fu_629_p1 = B_trunc_fu_619_p4;

assign zext_ln1454_fu_520_p1 = Mx_zeros_reg_1265;

assign zext_ln1488_fu_583_p1 = Mx_V_reg_1277;

assign zext_ln541_1_fu_347_p1 = lshr_ln_fu_337_p4;

assign zext_ln541_fu_683_p1 = p_Result_63_fu_676_p3;

assign zext_ln841_fu_517_p1 = Mx_zeros_reg_1265;

assign zext_ln930_fu_362_p1 = trunc_ln628_reg_1223;

always @ (posedge ap_clk) begin
    p_Result_64_reg_1432[15:0] <= 16'b1000000000000000;
    p_Result_65_reg_1437[18:0] <= 19'b1000000000000000000;
end

endmodule //threed_render_hls_sin_or_cos_float_s
